[book]
authors = ["Gabor Szabo"]
language = "en"
src = "src"
title = "Public mdBooks"
description = "Every publicly available mdbook"


# Add github icon to the menu
[output.html]
git-repository-url = "https://github.com/szabgab/public-mdbooks"
git-repository-icon = "fa-github"

# Remove the printer icon from the menu
[output.html.print]
enable = false

[output.html.fold]
enable = true
level = 0

# Handle Youtube video embedding and the footer
[preprocessor.embedify]
footer.enable = true
footer.message = "Copyright © 2025 • Created with ❤️  by [Gábor Szabó](https://szabgab.com/)"

